### ISSUE TITLE
name 'torch' is not defined

### ISSUE THREAD

**Issue by ScrubADuck** [justin-bennington/S2ML-Generators#12]
When trying to run this it comes with the issue of torch not being defined and as some one who knows little to nothing of code I do not know how to fix this. Many thanks for any help. 

torch.cuda.empty_cache()
with torch.no_grad():
    torch.cuda.empty_cache()

**Comment by justin-bennington** [comment]
If you have run this block before the installation + setup blocks (each time), torch will reference nothing
