### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.keras.engine.keras_tensor'

### ISSUE THREAD

**Issue by benjismith** [justin-bennington/S2ML-Generators#14]
I just started seeing this error when running this notebook on Colab recently, during the "Load libraries and definitions" block. Here's a screenshot...

<img width="1322" alt="Screen Shot 2021-11-13 at 10 14 54 AM" src="https://user-images.githubusercontent.com/458075/141654759-0da87ee9-e512-4194-81bc-c4ec9acdc352.png">

I've run hundreds of cycles of this notebook in the past, but within the last week or two, it started failing every time.

I'm not an experienced python dev, so I'm a bit out of my element, but I can help troubleshoot from my side if that helps!

**Comment by justin-bennington** [comment]
hey Benji -- just checking in here, are you still getting this error? can't reproduce on my end

**Comment by benjismith** [comment]
Hey yeah, it turns out I was running an older version of this notebook (in my own fork, where I've made other tweaks), and it was the ISR dependency that was causing the problem. When I got rid of ISR, the problem went away. Thanks for taking a look!!
