### ISSUE TITLE
Color problem in ESRGAN output

### ISSUE THREAD

**Issue by geoffpowell** [justin-bennington/S2ML-Generators#9]
I thought ESRGAN was simply inverting the colors of the original but I took the image results of ESRGAN into a graphics program and this isn't the case. Hue is shifted in parts of the image, and maintained in other parts. 
Examples attached. The original is in blue and green, ESRGAN's result gave a red background but foreground elements are maintained somehow. I have my own drive folder that I upscale images from, but ESRGAN still changes the colors even if you change the target directory to '../ESRGAN/LR/' to use the given example images. 

![0200](https://user-images.githubusercontent.com/11684998/136256652-0d318604-57a6-4fd8-9f19-58b148f2f2ee.png)

![0200](https://user-images.githubusercontent.com/11684998/136256777-8cd523aa-ea18-4f16-a75e-d69a397e4efb.png)
`

**Comment by justin-bennington** [comment]
Fixed in Version 1.5.4
